### ISSUE TITLE
compile error in bootloader with latest commit (12th July 2019)

### ISSUE THREAD

**Issue by ghost** [4ms/SWN#1]
compile error in bootloader with latest commit (12th July 2019) 

Code was removed in "WIP: DMA of I2C” update of
..../SWN/inc/drivers/pca9685_driver.h

(It’s a trivial one line code change to fix)

-----8<-----

bootloader.cc: In function 'int main()':
bootloader.cc:314:2: error: 'LEDDriver_Init' was not declared in this scope
  LEDDriver_Init(10);
  ^~~~~~~~~~~~~~
bootloader.cc:314:2: note: suggested alternative: 'LEDDriver_init_dma'
  LEDDriver_Init(10);
  ^~~~~~~~~~~~~~
  LEDDriver_init_dma
Makefile:144: recipe for target 'build/bootloader/bootloader.o' failed
make: *** [build/bootloader/bootloader.o] Error 1

**Comment by danngreen** [comment]
Thanks for the find! I corrected it and pushed the fix
Note: it actually should be 
`LEDDriver_init_direct(10);`
Not
`LEDDriver_init_dma(10);`

**Comment by ghost** [comment]
Thanks Dan - yes, that’s what I’ve been using in my boot loader !

Amazing module by the way !!! Been playing with it heaps today !
Trying to think of any improvements - I’ve been combing through the code but the UI is pretty dense as it is :-)
Just wondering about normalling v/oct of A channel to the others to add with the lfo inputs as cv to create chords….

Thanks
Andy

Ps (I was finishing the module when I realised one of my first ever diy builds, years ago, was the tremulus lune
- drew the pcb tracks with a sharpie and etched it - didn’t have a clue what I was doing but I still use that pedal today :-) )
