### ISSUE TITLE
Schematic incorrect (pdf and kicad) lists stm32 as STM32F42xZ

### ISSUE THREAD

**Issue by ghost** [4ms/SWN#2]
As of 29/8/19 v1.1 hardware:

Schematic (pdf and kicad) lists stm32 as STM32F42xZ (pcbs, Makefile and BOM export list it as STM32F765ZGT)

**Comment by danngreen** [comment]
That's correct, the kicad symbol name is STM32F42x, and it's identical to the F765 but should be named properly. I fixed it.
